### ISSUE TITLE
lxml issue

### ISSUE THREAD

**Issue by kiraoftheweb** [backslash/Webscrapers-Bots#1]
So there's the error

Traceback (most recent call last):  File "main.py", line 21, in <module>
    soup = BeautifulSoup(CONTENT, 'lxml')  File "/home/runner/.local/share/virtualenvs/python3/lib/pythopython3.8/site-packages/bs4/__init__.py", line 225, in __init__    raise FeatureNotFound(                                pytho
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a pas)rser library?

**Comment by backslash** [comment]
`pip install lxml` should fix that, if not you can change it to `html` instead and that should fix it. If that doesn't let me know.

**Comment by kiraoftheweb** [comment]
fixed.
